#!/usr/bin/env python3
"""
Перевод всех highlight блоков для английской и испанской версий
"""

import re
from pathlib import Path

# Словари переводов для highlight блоков
highlight_translations = {
    'en': {
        # Общие фразы
        'самый яркий танцор года': 'the brightest dancer of the year',
        'Абсолютный лидер по победам': 'Absolute leader by wins',
        'получал поинты на': 'earned points at',
        'получала поинты на': 'earned points at',
        'был одинаково успешен и как лидер, и как фолловер': 'was equally successful as both leader and follower',
        'Продемонстрировал исключительно высокий процент побед': 'Demonstrated exceptionally high win rate',
        'в All-Stars за лидера': 'in All-Stars as leader',
        'в Advanced за фолловера': 'in Advanced as follower',
        'побеждал во всех регионах мира': 'won in all regions of the world',
        'что является совершенно уникальным достижением': 'which is a completely unique achievement',
        'добился уникального достижения': 'achieved a unique feat',
        'единственный в топе': 'the only one in the top',
        'кто побеждал и в номинации Champions': 'who won in both Champions division',
        'и в номинации All-Stars за обе роли': 'and All-Stars in both roles',
        'Всего': 'Total',
        'побед': 'wins',
        'демонстрируя универсальность на самом высоком уровне': 'demonstrating versatility at the highest level',
        'лидер по набранным поинтам': 'leader by points earned',
        'и по количеству ивентов с поинтами': 'and by number of events with points',
        'в трех номинациях': 'in three divisions',
        'выступая в обеих ролях': 'competing in both roles',
        'раз как фолловер': 'times as follower',
        'раз как лидер': 'times as leader',
        'одержав при этом': 'achieving',
        'побед': 'wins',
        'абсолютное доминирование в Champions': 'absolute dominance in Champions',
        'лидер и по поинтам': 'leader by both points',
        'и по победам': 'and wins',
        'полученным и одержанным на': 'earned and won at',
        'ивентах': 'events',
        'впечатляющий результат в Advanced': 'impressive result in Advanced',
        'побед из': 'wins out of',
        'участий': 'participations',
        'как фолловер': 'as follower',
        'как следствие': 'as a result',
        'место по поинтам': 'place by points',
        'набранным в этой номинации в 2025 году': 'earned in this division in 2025',
        'Еще на одном ивенте успела получить поинты в All-Stars': 'Also earned points in All-Stars at one more event',
        'наибольшее разнообразие номинаций в топе': 'greatest diversity of divisions in the top',
        'получала поинты в четырех номинациях': 'earned points in four divisions',
        'Показала эффективный рост': 'Showed effective growth',
        'закрыла': 'closed',
        'и набрала первые поинты All-Stars за фолловера': 'and earned first All-Stars points as follower',
        'параллельно успешно выступая как лидер': 'while also successfully competing as leader',
        'еще один пример впечатляющего прогресса': 'another example of impressive progress',
        'начав в январе в Intermediate': 'starting in January in Intermediate',
        'успел закрыть Advanced и набрать поинты в All-Stars': 'managed to close Advanced and earn points in All-Stars',
        'в течение 2025 года': 'during 2025',
        'набрав в итоге': 'earning a total of',
        'поинтов': 'points',
        'Один из самых быстрорастущих по дивизионам танцоров': 'One of the fastest-growing dancers across divisions',
        'в 2025 году': 'in 2025',
        'абсолютный лидер по поинтам в All-Stars': 'absolute leader by points in All-Stars',
        'набрал': 'earned',
        'в этой номинации': 'in this division',
        'что составляет основную часть его результата': 'which constitutes the main part of his result',
        'поинтов всего': 'points total',
        'вторая по поинтам в All-Stars': 'second by points in All-Stars',
        'набрала': 'earned',
        'показав высокую результативность и стабильность результатов': 'showing high performance and consistent results',
        'успешно дебютировала на The Open в Showcase': 'successfully debuted at The Open in Showcase',
        'третий по поинтам в All-Stars за лидера': 'third by points in All-Stars as leader',
        'плюс': 'plus',
        'в Champions': 'in Champions',
        'Сохраняет стабильно высокий уровень': 'Maintains consistently high level',
        'в 2024 году набрал': 'in 2024 earned',
        'с': 'with',
        'победами на': 'wins at',
        'ивентах': 'events',
        'демонстрируя завидное постоянство и высокие результаты': 'demonstrating enviable consistency and high results',
        'а также один раз побеждал в Австралии': 'and also won once in Australia',
        
        # География
        'География:': 'Geography:',
        'все поинты': 'all points',
        'набрал на': 'earned at',
        'набрала на': 'earned at',
        'на европейских ивентах': 'at European events',
        'на американских ивентах': 'at American events',
        'на российских ивентах': 'at Russian events',
        'на испанских ивентах': 'at Spanish events',
        'на французских ивентах': 'at French events',
        'все': 'all',
        'побед одержаны': 'wins achieved',
        'побед одержана': 'wins achieved',
        'получены': 'earned',
        'на ивентах в США': 'at events in the USA',
        'победы: семь в США, три в Европе': 'wins: seven in USA, three in Europe',
        'в Северной Америке': 'in North America',
        'одна победа': 'one win',
        'три победы': 'three wins',
        'все четыре победы в США': 'all four wins in USA',
        'все семь побед в США': 'all seven wins in USA',
        'все пять побед': 'all five wins',
        'все семь побед одержаны в Европе': 'all seven wins achieved in Europe',
        
        # События
        'Самый успешный ивент:': 'Most successful event:',
        'Самые успешные ивенты:': 'Most successful events:',
        'по': 'by',
        'поинтов': 'points',
        'поинта': 'points',
        'поинта каждый': 'points each',
        'за каждый': 'each',
        'уникальное достижение на': 'unique achievement at',
        'выиграл две старшие номинации на одном ивенте': 'won two senior divisions at one event',
        
        # Европейские highlight блоки
        'удивительное достижение от юной девушки': 'amazing achievement from a young girl',
        'в ноябре отмечалась победой в Juniors': 'celebrated a win in Juniors in November',
        'которая заняла': 'who placed',
        'место по поинтам на европейских ивентах': 'place by points at European events',
        'Выступала исключительно на французских ивентах': 'Competed exclusively at French events',
        'в Intermediate и Advanced за фолловера': 'in Intermediate and Advanced as follower',
        'и в Intermediate за лидера': 'and in Intermediate as leader',
        'демонстрируя стабильно высокие результаты': 'demonstrating consistently high results',
        'Получала поинты на': 'Earned points at',
        'ивентах': 'events',
        'одержала две победы': 'achieved two wins',
        'лидер по победам на европейских ивентах': 'leader by wins at European events',
        'в номинации в All-Stars': 'in All-Stars division',
        'отметился уникальным достижением': 'marked a unique achievement',
        'победив на трех подряд ивентах': 'winning at three consecutive events',
        'за 3 недели октября и ноября 2025 года': 'over 3 weeks in October and November 2025',
        'Набрал': 'Earned',
        'место по количеству ивентов с поинтами': 'place by number of events with points',
        'Все поинты набрал в высшей номинации All-Stars': 'All points earned in the highest All-Stars division',
        'заняв по этому показателю': 'placing',
        'место': 'place',
        'Также успешно дебютировал на The Open в номинации Classic': 'Also successfully debuted at The Open in Classic division',
        'место по поинтам набранным в номинации All-Stars': 'place by points earned in All-Stars division',
        'и разделил': 'and tied',
        'место по ивентам с поинтами': 'place by events with points',
        'а также одержал три победы': 'and also achieved three wins',
        'разделил': 'tied',
        'место по победам': 'place by wins',
        'Один из 5 танцоров': 'One of 5 dancers',
        'кто получал в 2025 поинты в номинации All-Stars и за лидера, и за фолловера': 'who earned points in All-Stars division in both leader and follower roles in 2025',
        'лидирует по поинтам в номинации All-Stars среди фолловеров': 'leads by points in All-Stars division among followers',
        'и делит': 'and ties',
        'место по количеству ивентов с поинтами': 'place by number of events with points',
        'что также является лучшим результатом для фолловеров': 'which is also the best result for followers',
        'место по поинтам на европейских ивентах': 'place by points at European events',
        'Универсальный танцор': 'Versatile dancer',
        'получал поинты в': 'earned points in',
        'номинациях': 'divisions',
        'и в обеих ролях': 'and in both roles',
        'фолловер и лидер': 'follower and leader',
        'Продемонстрировал высокую результативность': 'Demonstrated high performance',
        'три победы из восьми ивентов с поинтами': 'three wins out of eight events with points',
        'Еще один раз победил на The Open в Advanced за фолловера': 'Also won once at The Open in Advanced as follower',
        
        # Российские highlight блоки
        'абсолютный лидер российского рейтинга по поинтам': 'absolute leader of Russian ranking by points',
        'и одна из лидеров по количеству ивентов с поинтами': 'and one of the leaders by number of events with points',
        'выступая в двух ролях в двух номинациях': 'competing in two roles in two divisions',
        'Одержала две победы': 'Achieved two wins',
        'по одной в каждой роли': 'one in each role',
        'лидер по победам среди российских танцоров': 'leader by wins among Russian dancers',
        'и единственный с победой в Champions': 'and the only one with a win in Champions',
        'помимо еще трех побед в All-Stars': 'besides three more wins in All-Stars',
        'показав высокую результативность': 'showing high performance',
        'четыре победы из девяти ивентов': 'four wins out of nine events',
        'где набирал поинты': 'where points were earned',
        'лидер по количеству ивентов с поинтами среди российских танцоров': 'leader by number of events with points among Russian dancers',
        'Получила право соревоваться в Champions': 'Earned the right to compete in Champions',
        'впечатляющий дебютный год': 'impressive debut year',
        'получала поинты на': 'earned points at',
        'выступая в двух ролях в номинациях': 'competing in two roles in divisions',
        'раз как фолловер': 'times as follower',
        'раз как лидер': 'times as leader',
        'вторая в российском рейтинге по поинтам': 'second in Russian ranking by points',
        'продемонстрировав универсальность': 'demonstrating versatility',
        'в Novice за лидера': 'in Novice as leader',
        'в Intermediate за фолловера': 'in Intermediate as follower',
        'одержав здесь две победы': 'achieving two wins here',
        'одна из самых стабильных российских участниц': 'one of the most consistent Russian participants',
        'вошла во все три топ-10': 'entered all three top-10',
        'по поинтам': 'by points',
        'по победам': 'by wins',
        'по ивентам': 'by events',
        'Все': 'All',
        'выступлений с поинтами': 'performances with points',
        'в номинации Advanced': 'in Advanced division',
        'лидер по поинтам в All-Stars среди российских танцоров': 'leader by points in All-Stars among Russian dancers',
        'набрала': 'earned',
        'в этой номинации': 'in this division',
        'из': 'out of',
        'поинтов всего': 'points total',
        'демонстрируя высокий уровень в этой номинации': 'demonstrating high level in this division',
        'выступая в All-Stars за фоловера': 'competing in All-Stars as follower',
        'и в Intermediate за лидера': 'and in Intermediate as leader',
        
        # Sophisticated highlight блоки
        'лидер по поинтам в Sophisticated': 'leader by points in Sophisticated',
        'и разделила': 'and tied',
        'место по победам': 'place by wins',
        'среди танцоров Sophisticated': 'among Sophisticated dancers',
        'Получила поинты на': 'Earned points at',
        'ивентах': 'events',
        'место по поинтам': 'place by points',
        'место по победам': 'place by wins',
        'Получил поинты на': 'Earned points at',
        'показав высокую результативность': 'showing high performance',
        'шесть побед из девяти ивентов': 'six wins out of nine events',
        'разделил': 'tied',
        'место по поинтам': 'place by points',
        'и': 'and',
        'место по ивентам': 'place by events',
        'Одержал две победы': 'Achieved two wins',
        'Побеждал в двух регионах': 'Won in two regions',
        'Европе и Азии': 'Europe and Asia',
        'лидер по победам в Sophisticated': 'leader by wins in Sophisticated',
        'Получил поинты на': 'Earned points at',
        
        # Испанские highlight блоки
        'Испанский танцор года': 'Spanish Dancer of the Year',
        'место по полученным поинтам': 'place by points earned',
        'лидер по победам': 'leader by wins',
        'место по ивентам': 'place by events',
        'среди испанских танцоров': 'among Spanish dancers',
        'Все поинты набрал в Advanced номинации': 'All points earned in Advanced division',
        'Остался один шаг от перехода в номинацию All-Stars': 'One step away from advancing to All-Stars division',
        'Самый активно прогрессирующий испанский танцор в 2025': 'Most actively progressing Spanish dancer in 2025',
        'абсолютный лидер по ивентам с поинтами': 'absolute leader by events with points',
        'лидер по набранным поинтам среди испанских танцоров': 'leader by points earned among Spanish dancers',
        'Одержал одну победу в Intermediate': 'Achieved one win in Intermediate',
        'лидер по победам среди испанских танцоров': 'leader by wins among Spanish dancers',
        'разделил': 'tied',
        'место с': 'place with',
        'место по поинтам': 'place by points',
        'место по ивентам среди испанских танцоров': 'place by events among Spanish dancers',
        'Все поинты набрал в номинации All-Stars': 'All points earned in All-Stars division',
    },
    'es': {
        # Общие фразы
        'самый яркий танцор года': 'el bailarín más destacado del año',
        'Абсолютный лидер по победам': 'Líder absoluto por victorias',
        'получал поинты на': 'obtuvo puntos en',
        'получала поинты на': 'obtuvo puntos en',
        'был одинаково успешен и как лидер, и как фолловер': 'fue igualmente exitoso como líder y seguidor',
        'Продемонстрировал исключительно высокий процент побед': 'Demostró un porcentaje excepcionalmente alto de victorias',
        'в All-Stars за лидера': 'en All-Stars como líder',
        'в Advanced за фолловера': 'en Advanced como seguidor',
        'побеждал во всех регионах мира': 'ganó en todas las regiones del mundo',
        'что является совершенно уникальным достижением': 'lo cual es un logro completamente único',
        'добился уникального достижения': 'logró una hazaña única',
        'единственный в топе': 'el único en el top',
        'кто побеждал и в номинации Champions': 'que ganó tanto en la división Champions',
        'и в номинации All-Stars за обе роли': 'como en All-Stars en ambos roles',
        'Всего': 'Total',
        'побед': 'victorias',
        'демонстрируя универсальность на самом высоком уровне': 'demostrando versatilidad al más alto nivel',
        'лидер по набранным поинтам': 'líder por puntos obtenidos',
        'и по количеству ивентов с поинтами': 'y por número de eventos con puntos',
        'в трех номинациях': 'en tres divisiones',
        'выступая в обеих ролях': 'compitiendo en ambos roles',
        'раз как фолловер': 'veces como seguidor',
        'раз как лидер': 'veces como líder',
        'одержав при этом': 'logrando',
        'абсолютное доминирование в Champions': 'dominio absoluto en Champions',
        'лидер и по поинтам': 'líder tanto por puntos',
        'и по победам': 'como por victorias',
        'полученным и одержанным на': 'obtenidos y ganados en',
        'ивентах': 'eventos',
        'впечатляющий результат в Advanced': 'resultado impresionante en Advanced',
        'побед из': 'victorias de',
        'участий': 'participaciones',
        'как фолловер': 'como seguidor',
        'как следствие': 'como resultado',
        'место по поинтам': 'lugar por puntos',
        'набранным в этой номинации в 2025 году': 'obtenidos en esta división en 2025',
        'Еще на одном ивенте успела получить поинты в All-Stars': 'También obtuvo puntos en All-Stars en un evento más',
        'наибольшее разнообразие номинаций в топе': 'mayor diversidad de divisiones en el top',
        'получала поинты в четырех номинациях': 'obtuvo puntos en cuatro divisiones',
        'Показала эффективный рост': 'Mostró crecimiento efectivo',
        'закрыла': 'cerró',
        'и набрала первые поинты All-Stars за фолловера': 'y obtuvo los primeros puntos de All-Stars como seguidor',
        'параллельно успешно выступая как лидер': 'mientras también competía exitosamente como líder',
        'еще один пример впечатляющего прогресса': 'otro ejemplo de progreso impresionante',
        'начав в январе в Intermediate': 'comenzando en enero en Intermediate',
        'успел закрыть Advanced и набрать поинты в All-Stars': 'logró cerrar Advanced y obtener puntos en All-Stars',
        'в течение 2025 года': 'durante 2025',
        'набрав в итоге': 'obteniendo en total',
        'поинтов': 'puntos',
        'Один из самых быстрорастущих по дивизионам танцоров': 'Uno de los bailarines de más rápido crecimiento entre divisiones',
        'абсолютный лидер по поинтам в All-Stars': 'líder absoluto por puntos en All-Stars',
        'набрал': 'obtuvo',
        'в этой номинации': 'en esta división',
        'что составляет основную часть его результата': 'lo que constituye la mayor parte de su resultado',
        'поинтов всего': 'puntos en total',
        'вторая по поинтам в All-Stars': 'segunda por puntos en All-Stars',
        'набрала': 'obtuvo',
        'показав высокую результативность и стабильность результатов': 'mostrando alto rendimiento y resultados consistentes',
        'успешно дебютировала на The Open в Showcase': 'debutó exitosamente en The Open en Showcase',
        'третий по поинтам в All-Stars за лидера': 'tercero por puntos en All-Stars como líder',
        'плюс': 'más',
        'в Champions': 'en Champions',
        'Сохраняет стабильно высокий уровень': 'Mantiene un nivel consistentemente alto',
        'в 2024 году набрал': 'en 2024 obtuvo',
        'с': 'con',
        'победами на': 'victorias en',
        'демонстрируя завидное постоянство и высокие результаты': 'demostrando constancia envidiable y altos resultados',
        'а также один раз побеждал в Австралии': 'y también ganó una vez en Australia',
        
        # География
        'География:': 'Geografía:',
        'все поинты': 'todos los puntos',
        'набрал на': 'obtuvo en',
        'набрала на': 'obtuvo en',
        'на европейских ивентах': 'en eventos europeos',
        'на американских ивентах': 'en eventos americanos',
        'на российских ивентах': 'en eventos rusos',
        'на испанских ивентах': 'en eventos españoles',
        'на французских ивентах': 'en eventos franceses',
        'все': 'todas',
        'побед одержаны': 'victorias logradas',
        'побед одержана': 'victorias logradas',
        'получены': 'obtenidos',
        'на ивентах в США': 'en eventos en EE.UU.',
        'победы: семь в США, три в Европе': 'victorias: siete en EE.UU., tres en Europa',
        'в Северной Америке': 'en América del Norte',
        'одна победа': 'una victoria',
        'три победы': 'tres victorias',
        'все четыре победы в США': 'todas las cuatro victorias en EE.UU.',
        'все семь побед в США': 'todas las siete victorias en EE.UU.',
        'все пять побед': 'todas las cinco victorias',
        'все семь побед одержаны в Европе': 'todas las siete victorias logradas en Europa',
        
        # События
        'Самый успешный ивент:': 'Evento más exitoso:',
        'Самые успешные ивенты:': 'Eventos más exitosos:',
        'по': 'por',
        'поинтов': 'puntos',
        'поинта': 'puntos',
        'поинта каждый': 'puntos cada uno',
        'за каждый': 'cada uno',
        'уникальное достижение на': 'logro único en',
        'выиграл две старшие номинации на одном ивенте': 'ganó dos divisiones senior en un evento',
        
        # Европейские highlight блоки
        'удивительное достижение от юной девушки': 'logro sorprendente de una joven',
        'в ноябре отмечалась победой в Juniors': 'celebrada con una victoria en Juniors en noviembre',
        'которая заняла': 'que ocupó',
        'место по поинтам на европейских ивентах': 'lugar por puntos en eventos europeos',
        'Выступала исключительно на французских ивентах': 'Compitió exclusivamente en eventos franceses',
        'в Intermediate и Advanced за фолловера': 'en Intermediate y Advanced como seguidor',
        'и в Intermediate за лидера': 'y en Intermediate como líder',
        'демонстрируя стабильно высокие результаты': 'demostrando resultados consistentemente altos',
        'Получала поинты на': 'Obtuvo puntos en',
        'ивентах': 'eventos',
        'одержала две победы': 'logró dos victorias',
        'лидер по победам на европейских ивентах': 'líder por victorias en eventos europeos',
        'в номинации в All-Stars': 'en la división All-Stars',
        'отметился уникальным достижением': 'marcó un logro único',
        'победив на трех подряд ивентах': 'ganando en tres eventos consecutivos',
        'за 3 недели октября и ноября 2025 года': 'durante 3 semanas en octubre y noviembre de 2025',
        'Набрал': 'Obtuvo',
        'место по количеству ивентов с поинтами': 'lugar por número de eventos con puntos',
        'Все поинты набрал в высшей номинации All-Stars': 'Todos los puntos obtenidos en la división más alta All-Stars',
        'заняв по этому показателю': 'ocupando',
        'место': 'lugar',
        'Также успешно дебютировал на The Open в номинации Classic': 'También debutó exitosamente en The Open en la división Classic',
        'место по поинтам набранным в номинации All-Stars': 'lugar por puntos obtenidos en la división All-Stars',
        'и разделил': 'y empató',
        'место по ивентам с поинтами': 'lugar por eventos con puntos',
        'а также одержал три победы': 'y también logró tres victorias',
        'разделил': 'empató',
        'место по победам': 'lugar por victorias',
        'Один из 5 танцоров': 'Uno de los 5 bailarines',
        'кто получал в 2025 поинты в номинации All-Stars и за лидера, и за фолловера': 'que obtuvo puntos en la división All-Stars tanto como líder como seguidor en 2025',
        'лидирует по поинтам в номинации All-Stars среди фолловеров': 'lidera por puntos en la división All-Stars entre seguidores',
        'и делит': 'y empató',
        'место по количеству ивентов с поинтами': 'lugar por número de eventos con puntos',
        'что также является лучшим результатом для фолловеров': 'lo cual también es el mejor resultado para seguidores',
        'место по поинтам на европейских ивентах': 'lugar por puntos en eventos europeos',
        'Универсальный танцор': 'Bailarín versátil',
        'получал поинты в': 'obtuvo puntos en',
        'номинациях': 'divisiones',
        'и в обеих ролях': 'y en ambos roles',
        'фолловер и лидер': 'seguidor y líder',
        'Продемонстрировал высокую результативность': 'Demostró alto rendimiento',
        'три победы из восьми ивентов с поинтами': 'tres victorias de ocho eventos con puntos',
        'Еще один раз победил на The Open в Advanced за фолловера': 'También ganó una vez en The Open en Advanced como seguidor',
        
        # Испанские highlight блоки
        'Испанский танцор года': 'Bailarín Español del Año',
        'место по полученным поинтам': 'lugar por puntos obtenidos',
        'лидер по победам': 'líder por victorias',
        'место по ивентам': 'lugar por eventos',
        'среди испанских танцоров': 'entre bailarines españoles',
        'Все поинты набрал в Advanced номинации': 'Todos los puntos obtenidos en la división Advanced',
        'Остался один шаг от перехода в номинацию All-Stars': 'Quedó un paso del avance a la división All-Stars',
        'Самый активно прогрессирующий испанский танцор в 2025': 'Bailarín español más activamente progresivo en 2025',
        'абсолютный лидер по ивентам с поинтами': 'líder absoluto por eventos con puntos',
        'лидер по набранным поинтам среди испанских танцоров': 'líder por puntos obtenidos entre bailarines españoles',
        'Одержал одну победу в Intermediate': 'Logró una victoria en Intermediate',
        'лидер по победам среди испанских танцоров': 'líder por victorias entre bailarines españoles',
        'разделил': 'empató',
        'место с': 'lugar con',
        'место по поинтам': 'lugar por puntos',
        'место по ивентам среди испанских танцоров': 'lugar por eventos entre bailarines españoles',
        'Все поинты набрал в номинации All-Stars': 'Todos los puntos obtenidos en la división All-Stars',
    }
}

def translate_highlight_block(block, lang):
    """Переводит один highlight блок"""
    t = highlight_translations[lang]
    result = block
    
    # Применяем все замены из словаря
    for ru_text, translated_text in t.items():
        result = result.replace(ru_text, translated_text)
    
    return result

def translate_all_highlights(content, lang):
    """Переводит все highlight блоки в контенте"""
    # Находим все highlight блоки
    pattern = r'<div class="highlight-insight"[^>]*>.*?</div>\s*</div>'
    blocks = re.findall(pattern, content, re.DOTALL)
    
    result = content
    for block in blocks:
        translated_block = translate_highlight_block(block, lang)
        result = result.replace(block, translated_block)
    
    return result

# Читаем файлы
en_file = Path('dancers_2025_en.html')
es_file = Path('dancers_2025_es.html')

print("Перевод highlight блоков для английской версии...")
with open(en_file, 'r', encoding='utf-8') as f:
    en_content = f.read()

# Переводим highlight блоки
en_content = translate_all_highlights(en_content, 'en')

with open(en_file, 'w', encoding='utf-8') as f:
    f.write(en_content)
print("✅ Английская версия обновлена")

print("\nПеревод highlight блоков для испанской версии...")
with open(es_file, 'r', encoding='utf-8') as f:
    es_content = f.read()

# Переводим highlight блоки
es_content = translate_all_highlights(es_content, 'es')

with open(es_file, 'w', encoding='utf-8') as f:
    f.write(es_content)
print("✅ Испанская версия обновлена")

print("\n⚠️  Некоторые сложные фразы могут требовать ручной проверки.")
