import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / 'article_division_transition_time.html'
TARGET_EN = ROOT / 'article_division_transition_time_en.html'
TARGET_ES = ROOT / 'article_division_transition_time_es.html'


def translate_file(source_file, target_file, lang, translations):
    content = source_file.read_text(encoding='utf-8')

    content = re.sub(r'<html lang="ru">', f'<html lang="{lang}">', content)

    content = re.sub(
        r'<button class="lang-btn active" data-lang="ru" aria-label="Переключить на русский язык" aria-pressed="true">RU</button>',
        r'<button class="lang-btn" data-lang="ru" aria-label="Переключить на русский язык" aria-pressed="false">RU</button>',
        content,
    )

    if lang == 'en':
        content = re.sub(
            r'<button class="lang-btn" data-lang="en" aria-label="Switch to English" aria-pressed="false">EN</button>',
            r'<button class="lang-btn active" data-lang="en" aria-label="Switch to English" aria-pressed="true">EN</button>',
            content,
        )
        content = re.sub(
            r"var ARTICLE_ID = 'article_division_transition_ru';",
            "var ARTICLE_ID = 'article_division_transition_en';",
            content,
        )
        content = content.replace('article_division_transition_ru_', 'article_division_transition_en_')
    elif lang == 'es':
        content = re.sub(
            r'<button class="lang-btn" data-lang="es" aria-label="Cambiar a español" aria-pressed="false">ES</button>',
            r'<button class="lang-btn active" data-lang="es" aria-label="Cambiar a español" aria-pressed="true">ES</button>',
            content,
        )
        content = re.sub(
            r"var ARTICLE_ID = 'article_division_transition_ru';",
            "var ARTICLE_ID = 'article_division_transition_es';",
            content,
        )
        content = content.replace('article_division_transition_ru_', 'article_division_transition_es_')

    for ru_text in sorted(translations.keys(), key=len, reverse=True):
        content = content.replace(ru_text, translations[ru_text])

    if lang == 'en':
        content = content.replace(
            'https://wsdc-analytics.github.io/article_division_transition_time.html',
            'https://wsdc-analytics.github.io/article_division_transition_time_en.html',
        )
        content = content.replace(
            'https://wsdc-analytics.github.io/rules_evolution_2025.html?lang=ru',
            'https://wsdc-analytics.github.io/rules_evolution_2025_en.html?lang=en',
        )
        content = content.replace(
            'https://wsdc-analytics.github.io/article_3year_rule.html?lang=ru',
            'https://wsdc-analytics.github.io/article_3year_rule_en.html?lang=en',
        )
    elif lang == 'es':
        content = content.replace(
            'https://wsdc-analytics.github.io/article_division_transition_time.html',
            'https://wsdc-analytics.github.io/article_division_transition_time_es.html',
        )
        content = content.replace(
            'https://wsdc-analytics.github.io/rules_evolution_2025.html?lang=ru',
            'https://wsdc-analytics.github.io/rules_evolution_2025_es.html?lang=es',
        )
        content = content.replace(
            'https://wsdc-analytics.github.io/article_3year_rule.html?lang=ru',
            'https://wsdc-analytics.github.io/article_3year_rule_es.html?lang=es',
        )

    target_file.write_text(content, encoding='utf-8')


en_translations = {
    'Разбираем, не стала ли Skill Level-система WSDC двигаться быстрее, чем меняется соревновательный опыт танцоров.': 'We examine whether the WSDC Skill Level system has started moving faster than dancers\' competitive experience is changing.',
    'Ускорение переходов между дивизионами: Надо ли что-то делать?': 'Faster Division Transitions: Should Anything Be Done?',
    'Пороги, поинты и скорость переходов: что изменилось после восстановления календаря WSDC.': 'Thresholds, points, and transition speed: what changed after the WSDC calendar recovered.',
    'WSDC, West Coast Swing, Skill Level, дивизионы, переход, поинты, Novice, Intermediate, Advanced, All-Star, Champions, аналитика': 'WSDC, West Coast Swing, Skill Level, divisions, transition, points, Novice, Intermediate, Advanced, All-Star, Champions, analytics',
    'Не стала ли Skill Level-система двигаться быстрее, чем растёт соревновательный опыт?': 'Has the Skill Level system started moving faster than competitive experience is growing?',
    'Разбираем, не стала ли Skill Level-система WSDC двигаться быстрее, чем меняется соревновательный опыт танцоров': 'We examine whether the WSDC Skill Level system has started moving faster than dancers\' competitive experience is changing',
    'Перейти к содержимому': 'Skip to content',
    '← К главной': '← Back to Home',
    'Выбор языка': 'Language selection',
    'Что происходит с переходами между дивизионами, когда ивентов становится больше, а пороги остаются прежними': 'What happens to division transitions when there are more events but thresholds stay the same',
    'После пандемии WSDC-календарь стал активно расти. И вместе с ним изменилось ощущение самой системы дивизионов: поинтов стало больше, возможностей соревноваться — тоже, а путь до следующего дивизиона для части танцоров начал выглядеть короче. Появились случаи, когда танцоры за один календарный год проходят два–три дивизиона, и это перестаёт выглядеть чем-то уникальным.': 'After the pandemic, the WSDC calendar began growing rapidly. Along with it, the feel of the division system changed: there were more points, more opportunities to compete, and for some dancers the path to the next division started looking shorter. Cases where dancers move through two or three divisions in a single calendar year are no longer unusual.',
    'За 2025 год прошло <strong>172 ивента</strong>, почти <strong>4000 танцоров</strong> получили более <strong>46 тысяч поинтов</strong> — это рекордные показатели за весь период проведения WSDC-ивентов. Текущие показатели 2026 года не дают оснований предполагать, что этот восходящий тренд пойдёт на спад.': 'In 2025, there were <strong>172 events</strong>, nearly <strong>4,000 dancers</strong> earned more than <strong>46,000 points</strong> — record figures for the entire history of WSDC events. Early 2026 data gives no reason to expect this upward trend to reverse.',
    'В данной статье я хочу рассмотреть существующий механизм регулирования переходов между Skill Level-дивизионами WSDC, а также то, насколько хорошо или плохо текущие пороговые значения справляются с увеличением количества ивентов и танцоров в последние годы, и надо ли что-то с этим делать.': 'In this article, I want to examine the existing mechanism for regulating transitions between WSDC Skill Level divisions, how well current thresholds are coping with the growth in events and dancers in recent years, and whether anything should be done about it.',
    'Почему это важно': 'Why This Matters',
    'Пороги вроде <strong>16 поинтов</strong> для перехода из Novice в Intermediate или <strong>30</strong> из Intermediate в Advanced кажутся технической деталью. Но именно они задают темп: когда человеку уже можно идти в дивизион выше, а когда он должен туда идти.': 'Thresholds like <strong>16 points</strong> to move from Novice to Intermediate or <strong>30</strong> from Intermediate to Advanced may look like technical details. But they set the pace: when a dancer may move up, and when they must.',
    'Если пороги слишком высокие, танцоры надолго застревают в дивизионе и могут потерять мотивацию. Если слишком низкие — они быстрее получают право идти выше, но не всегда успевают накопить соревновательный опыт и танцевальное мастерство для нового уровня. В обоих случаях вопрос не только в правилах, но и в том, насколько пороги переходов помогают росту, а не просто фиксируют движение по дивизионам.': 'If thresholds are too high, dancers get stuck in a division and may lose motivation. If too low, they gain the right to move up sooner but do not always accumulate enough competitive experience and skill for the next level. In both cases, the question is not only about rules, but about whether transition thresholds support growth rather than merely recording movement through divisions.',
    'Реестр WSDC учитывает поинты и результаты на соревнованиях. Он не знает, сколько человек тренировался, насколько глубоко он понимает музыку и как выглядит его танец в зале. Поэтому важно отделять две вещи: <strong>скорость продвижения по дивизионам</strong> и <strong>рост танцевального мастерства</strong>. Они связаны, но не обязаны совпадать.': 'The WSDC registry tracks points and competition results. It does not know how much someone trained, how deeply they understand the music, or how they actually dance. So it is important to separate two things: <strong>speed of advancement through divisions</strong> and <strong>growth in dance skill</strong>. They are related, but they do not have to match.',
    'Чтобы понять, почему сравнение с прошлым периодом важно, коротко посмотрим, как менялись правила. С полной хронологией изменений можно ознакомиться в <a href="https://wsdc-analytics.github.io/rules_evolution_2025.html?lang=ru" class="rules-evolution-link">этой статье</a>.': 'To understand why comparison with the past matters, here is a brief look at how the rules changed. The full chronology is available in <a href="https://wsdc-analytics.github.io/rules_evolution_2025.html?lang=ru" class="rules-evolution-link">this article</a>.',
    'Как менялись правила переходов': 'How Transition Rules Changed',
    'Установлены базовые пороги переходов по Skill Level: Novice → Intermediate <strong>15</strong> (было 20), Intermediate → Advanced <strong>30</strong> (было 25), Advanced → All-Stars <strong>45</strong> (было 40). Для All-Stars учитываются только Advanced-поинты за <strong>последние 3 года</strong> — не за всю карьеру.': 'Baseline Skill Level transition thresholds were set: Novice → Intermediate <strong>15</strong> (was 20), Intermediate → Advanced <strong>30</strong> (was 25), Advanced → All-Stars <strong>45</strong> (was 40). For All-Stars, only Advanced points from the <strong>last 3 years</strong> count — not the entire career.',
    'Вводится система <strong>allowed / required</strong>: Novice <strong>16/30</strong> и Intermediate <strong>30/45</strong> — по сумме поинтов в соответствующем дивизионе; для перехода Advanced → All-Stars — <strong>45/60</strong> Advanced-поинтов, накопленных за <strong>последние 36 месяцев</strong>. WSDC отдельно фиксирует «можно идти выше» и «больше ниже идти не можешь». Изменился механизм, но пороги перехода в дивизион выше остались по сути прежними.': 'The <strong>allowed / required</strong> system was introduced: Novice <strong>16/30</strong> and Intermediate <strong>30/45</strong> — based on points in the corresponding division; for Advanced → All-Stars — <strong>45/60</strong> Advanced points accumulated over the <strong>last 36 months</strong>. WSDC separately marks "may move up" and "is no longer allowed to remain in the lower division." The mechanism changed, but thresholds for moving to the next division remained essentially the same.',
    'Для Advanced → All-Stars пороги поднимаются до <strong>60/90</strong>, 36-месячное окно снимается. Novice и Intermediate без изменений: <strong>16/30</strong> и <strong>30/45</strong>. WSDC увеличила пороги перехода из одной номинации в другую, чтобы замедлить трафик переходов из Advanced в All-Stars.': 'For Advanced → All-Stars, thresholds rise to <strong>60/90</strong> and the 36-month window is removed. Novice and Intermediate stay unchanged: <strong>16/30</strong> and <strong>30/45</strong>. WSDC raised transition thresholds to slow traffic from Advanced to All-Stars.',
    'Пандемия 2020–2021 годов резко сократила календарь и число переходов. Восстановление после 2023 года наложилось на утверждённые пороги, а рост сообщества в 2025 году поставил вопрос об их актуальности — что косвенно отразилось в <a href="https://wsdc-analytics.github.io/article_3year_rule.html?lang=ru" class="rules-evolution-link">дискуссии</a> о возвращении 36-месячного окна в старшие номинации.': 'The 2020–2021 pandemic sharply reduced the calendar and the number of transitions. Recovery after 2023 coincided with fixed thresholds, and community growth in 2025 raised questions about their relevance — reflected indirectly in the <a href="https://wsdc-analytics.github.io/article_3year_rule.html?lang=ru" class="rules-evolution-link">discussion</a> about restoring the 36-month window in upper divisions.',
    'Что показывают данные': 'What the Data Shows',
    'Возьмём для исследования две метрики:': 'We will use two metrics:',
    '<strong>Время от первого поинта до порога перехода</strong> — сколько времени проходит от первого поинта в дивизионе до получения количества поинтов, позволяющего перейти в следующий дивизион.': '<strong>Time from first point to transition threshold</strong> — how long it takes from the first point in a division to earning enough points to move to the next division.',
    '<strong>Время между первыми поинтами в дивизионах</strong> — сколько времени проходит от первого поинта в одном дивизионе до первого поинта в следующем дивизионе.': '<strong>Time between first points in divisions</strong> — how long it takes from the first point in one division to the first point in the next.',
    'В обоих случаях используется медиана — «серединное» время: у половины танцоров путь занял меньше этого срока, у половины — больше.': 'In both cases we use the median — the "middle" time: half of dancers took less than this, half took more.',
    'Для сравнения взяты три периода: базовый <strong>2015–2019</strong>, рекордный <strong>2025</strong> и текущий <strong>2026</strong> как показатель текущего тренда. Отдельно показана годовая динамика с 2015 по 2026 год. В фокусе — наиболее стабильные Skill Level-дивизионы: Novice, Intermediate и Advanced.': 'Three periods are compared: baseline <strong>2015–2019</strong>, record year <strong>2025</strong>, and current <strong>2026</strong> as an indicator of the ongoing trend. Year-by-year dynamics from 2015 through 2026 are shown separately. The focus is on the most stable Skill Level divisions: Novice, Intermediate, and Advanced.',
    '<em>All-Stars и Champions как стартовые дивизионы отдельно не исследовались: для этих номинаций данных недостаточно.</em>': '<em>All-Stars and Champions were not studied separately as starting divisions: there is not enough data for these categories.</em>',
    'Время до порога перехода': 'Time to Transition Threshold',
    'Время до порога перехода по годам': 'Time to transition threshold by year',
    'Время до порога перехода, месяцы по дивизионам': 'Time to transition threshold, months by division',
    'Время до порога перехода по годам и дивизионам': 'Time to transition threshold by year and division',
    'В базовом периоде 2015–2019 на то, чтобы получить право выступать в Intermediate, требовалось примерно <strong>12 месяцев</strong> от получения первого поинта в Novice. На переход из Intermediate в Advanced требовалось <strong>17 месяцев</strong>, а на переход из Advanced в All-Stars — около <strong>20 месяцев</strong>.': 'In the 2015–2019 baseline period, earning the right to compete in Intermediate took about <strong>12 months</strong> from the first Novice point. Moving from Intermediate to Advanced took <strong>17 months</strong>, and from Advanced to All-Stars about <strong>20 months</strong>.',
    'В 2025 году этот показатель составил <strong>9 месяцев</strong> в Novice, <strong>16 месяцев</strong> в Intermediate и <strong>21 месяц</strong> в Advanced. Тренд 2026 года показывает, что в Novice этот показатель уже ближе к <strong>6 месяцам</strong>, а в Intermediate — к <strong>13</strong>. Главный сигнал здесь — нижняя часть системы стала проходиться быстрее именно там, где пороги давно не менялись.': 'In 2025, this figure was <strong>9 months</strong> in Novice, <strong>16 months</strong> in Intermediate, and <strong>21 months</strong> in Advanced. The 2026 trend shows Novice already closer to <strong>6 months</strong> and Intermediate closer to <strong>13</strong>. The main signal: the lower part of the system is moving faster precisely where thresholds have not changed in years.',
    'Время между первыми поинтами в дивизионах': 'Time Between First Points in Divisions',
    'Время между первыми поинтами по годам': 'Time between first points by year',
    'Время между первыми поинтами в дивизионах, месяцы': 'Time between first points in divisions, months',
    'Время между первыми поинтами по годам и дивизионам': 'Time between first points by year and division',
    'По метрике <strong>времени между первыми поинтами в дивизионах</strong> картина согласуется с <strong>временем до порога перехода</strong>, но мягче. В период с 2015 по 2019 год от первого поинта в Novice до первого поинта в Intermediate проходило примерно <strong>17 месяцев</strong>, из Intermediate в Advanced — <strong>21 месяц</strong>, из Advanced в All-Stars — около <strong>25 месяцев</strong>.': 'By <strong>time between first points in divisions</strong>, the picture aligns with <strong>time to transition threshold</strong>, but more gently. From 2015 to 2019, from the first Novice point to the first Intermediate point took about <strong>17 months</strong>, from Intermediate to Advanced <strong>21 months</strong>, and from Advanced to All-Stars about <strong>25 months</strong>.',
    'В 2025 году эти показатели составили <strong>15</strong>, <strong>17</strong> и <strong>27 месяцев</strong> соответственно. Тренд 2026 года пока близок к <strong>15 месяцам</strong> на Novice, <strong>17–18</strong> на Intermediate и <strong>28</strong> на Advanced. То есть фактический переход тоже ускоряется на нижних ступенях, но не так резко, как формальное право идти выше.': 'In 2025, these figures were <strong>15</strong>, <strong>17</strong>, and <strong>27 months</strong> respectively. The 2026 trend is still close to <strong>15 months</strong> in Novice, <strong>17–18</strong> in Intermediate, and <strong>28</strong> in Advanced. Actual transitions are speeding up on the lower rungs too, but not as sharply as the formal right to move up.',
    'Дополнительно важно посмотреть на ещё две вещи: стало ли в целом <strong>больше переходов</strong> между дивизионами и выросла ли <strong>доля тех</strong>, кто получает первые поинты в соседних дивизионах в течение 12 месяцев.': 'Two more things matter: whether there are <strong>more transitions</strong> between divisions overall, and whether the <strong>share of dancers</strong> who earn first points in adjacent divisions within 12 months has grown.',
    'Число переходов по годам': 'Number of transitions by year',
    'Доля быстрых переходов за 12 месяцев': 'Share of fast transitions within 12 months',
    'Доля стартовавших, дошедших до следующего дивизиона за 12 месяцев': 'Share of starters who reached the next division within 12 months',
    'Как видно на графиках, в младших дивизионах ускорился не только путь отдельного танцора — расширился и трафик переходов. Количество переходов в <strong>2025</strong> году превысило доковидные показатели, а доля танцоров, которые в течение 12 месяцев успевали получить первые поинты в двух соседних дивизионах, выросла примерно на <strong>5 процентных пунктов</strong> в парах Novice → Intermediate и Intermediate → Advanced от общего числа танцоров, получивших поинты в младшем дивизионе.': 'As the charts show, in lower divisions not only individual paths sped up — the flow of transitions expanded too. The number of transitions in <strong>2025</strong> exceeded pre-pandemic levels, and the share of dancers who earned first points in two adjacent divisions within 12 months rose by about <strong>5 percentage points</strong> in the Novice → Intermediate and Intermediate → Advanced pairs, relative to all dancers who earned points in the lower division.',
    'Переходы в старших дивизионах': 'Transitions in Upper Divisions',
    'WSDC уже пробовала тормозить трафик переходов между Advanced и All-Stars — поэтому он важен как контрольный пример. По метрике <strong>времени между первыми поинтами</strong> для перехода Advanced → All-Stars <strong>не видно такого же сжатия сроков</strong>: медианное время до первых поинтов в All-Stars остаётся сопоставимым с доковидным периодом или даже чуть выше.': 'WSDC has already tried to slow the flow of dancers from Advanced to All-Stars — so this path is an important control case. By <strong>time between first points</strong> for Advanced → All-Stars, there is <strong>no comparable compression of timelines</strong>: median time to first All-Stars points remains similar to the pre-pandemic period or even slightly higher.',
    'При этом следует учитывать, что в 2015–2019 порог для перехода в All-Stars был <strong>45</strong> Advanced-поинтов с дополнительным ограничением в виде <strong>36-месячного</strong> окна, а с 2023 года — уже <strong>60</strong> Advanced-поинтов. WSDC подняла планку именно потому, что поток в All-Stars стал слишком быстрым. В <strong>2025–2026</strong> годах медианное время до первых поинтов в All-Stars (<strong>27–28 месяцев</strong>) уже <strong>почти догнало</strong> темп, при котором раньше достигался порог в 45 поинтов (около <strong>25 месяцев</strong> в 2015–2019). Повышение порога пока сдерживает трафик переходов, но приближение к «доковидной» скорости заметно — и это отдельный повод следить за динамикой в старших номинациях.': 'Note that in 2015–2019 the threshold for All-Stars was <strong>45</strong> Advanced points with an additional <strong>36-month</strong> window; since 2023 it has been <strong>60</strong> Advanced points. WSDC raised the bar because the flow into All-Stars had become too fast. In <strong>2025–2026</strong>, median time to first All-Stars points (<strong>27–28 months</strong>) has <strong>nearly caught up</strong> to the pace at which the 45-point threshold used to be reached (about <strong>25 months</strong> in 2015–2019). The higher threshold still holds back that flow, but the approach to "pre-pandemic" speed is visible — another reason to watch dynamics in upper divisions.',
    'Вопрос к порогам — без готового ответа': 'A Question About Thresholds — Without a Ready Answer',
    'Если пороги — лишь формальная отметка («набрал X — можешь идти»), рост переходов может быть естественным следствием более плотного календаря ивентов. Если же пороги — способ сглаживать трафик перехода между дивизионами, то неизменные <strong>16/30</strong> и <strong>30/45</strong> при более плотном графике в младших дивизионах заслуживают обсуждения: совпадает ли темп переходов с тем, какой соревновательный опыт WSDC хочет видеть внутри каждого дивизиона.': 'If thresholds are merely a formal marker ("earned X — you may move up"), more transitions may be a natural consequence of a denser event calendar. If thresholds are meant to smooth the flow between divisions, then unchanged <strong>16/30</strong> and <strong>30/45</strong> with a denser lower-division schedule deserve discussion: does the pace of transitions match the competitive experience WSDC wants within each division?',
    'Ниже — не рекомендация «поднять до N», а способ показать масштаб сдвига: <em>какими должны быть allowed-пороги, чтобы медианное время вернулось к доковидным значениям 2015–2019 гг.</em>': 'Below is not a recommendation to "raise to N," but a way to show the scale of the shift: <em>what allowed thresholds would need to be for median time to return to pre-pandemic 2015–2019 values.</em>',
    'Это не новый «лимит скорости» и не проект правила. Это арифметическая иллюстрация: она учитывает только календарную скорость в реестре, но не географию, мотивацию и качество танца.': 'This is not a new "speed limit" or a draft rule. It is an arithmetic illustration: it considers only calendar speed in the registry, not geography, motivation, or dance quality.',
    'Какими выглядели бы пороги при старом темпе движения': 'What Thresholds Would Look Like at the Old Pace',
    'Текущий порог': 'Current threshold',
    'Порог с учётом темпа 2025 года': 'Threshold adjusted for 2025 pace',
    'Порог с учётом тренда 2026 года': 'Threshold adjusted for 2026 trend',
    'Текущие allowed-пороги и два сценария пересчёта': 'Current allowed thresholds and two recalculation scenarios',
    'Для того чтобы медианное время набора поинтов в Novice до порога перехода в Intermediate вернулось к доковидным значениям, порог должен быть <strong>21</strong> поинт, а с учётом тренда 2026 года и расчётом на сохранение этого тренда — <strong>30</strong> поинтов. Для перехода из Intermediate в Advanced эти значения составляют <strong>32</strong> и <strong>44</strong> поинта соответственно.': 'For median time to earn enough Novice points to reach the Intermediate threshold to return to pre-pandemic values, the threshold would need to be <strong>21</strong> points; accounting for the 2026 trend and assuming it continues, <strong>30</strong> points. For Intermediate → Advanced, those values are <strong>32</strong> and <strong>44</strong> points respectively.',
    'Почему нельзя «просто поднять пороги»': 'Why You Cannot "Just Raise Thresholds"',
    'Доступ к ивентам распределён неравномерно. В регионах с плотным календарём (США, Европа) более высокий порог может означать «чуть дольше соревноваться». В регионах с несколькими ивентами в год — почти непреодолимый барьер. Любое ужесточение сильнее ударит по тем, у кого меньше возможностей набирать поинты и участвовать в ивентах, а также в развивающихся WCS-регионах.': 'Access to events is uneven. In regions with dense calendars (USA, Europe), a higher threshold may mean "compete a bit longer." In regions with only a few events per year, it can be an almost insurmountable barrier. Any tightening hits hardest those with fewer opportunities to earn points and attend events, as well as developing WCS regions.',
    'Статья не призывает к конкретному решению. Она показывает, что <strong>скорость продвижения по дивизионам и рост соревновательного мастерства — не одно и то же</strong>: реестр фиксирует поинты и переходы, а не часы в зале. Если сообщество считает, что система дивизионов должна отражать именно соревновательный опыт, а не только доступность ивентов, этот разрыв стоит обсуждать открыто.': 'This article is not calling for a specific solution. It shows that <strong>speed of advancement through divisions and growth in competitive skill are not the same thing</strong>: the registry records points and transitions, not hours in the studio. If the community believes the division system should reflect competitive experience, not just event availability, this gap is worth discussing openly.',
    'Вывод': 'Conclusion',
    'После восстановления календаря ивентов нижняя часть Skill Level-системы WSDC стала проходиться быстрее и для большего количества танцоров, чем в 2015–2019: сжались сроки и до порога перехода, и между первыми поинтами в дивизионах, выросла доля быстрых переходов за год. На Advanced → All-Stars, где WSDC в 2023 году подняла пороги, массового ускорения нет — но темп переходов снова приближается к доковидному.': 'After the event calendar recovered, the lower part of the WSDC Skill Level system is moving faster for more dancers than in 2015–2019: timelines to the transition threshold and between first points in divisions have compressed, and the share of fast transitions within a year has grown. On Advanced → All-Stars, where WSDC raised thresholds in 2023, there is no mass acceleration — but transition pace is approaching pre-pandemic levels again.',
    'Это не доказательство, что танцоры «не готовы», и не призыв срочно поднять пороги. Реестр считает движение между дивизионами, но не измеряет опыт в зале; любое ужесточение бьёт неравномерно по регионам. Главный вопрос остаётся открытым: <strong>какую скорость движения по дивизионам WSDC считает здоровой</strong> — и где эта скорость перестаёт совпадать с ростом реального танцевального уровня.': 'This is not proof that dancers are "not ready," and not a call to raise thresholds urgently. The registry counts movement between divisions but does not measure real-world dance experience; any tightening hits regions unevenly. The main question remains open: <strong>what pace of movement through divisions does WSDC consider healthy</strong> — and where does that pace stop matching actual dance-level growth.',
    'Оценка статьи': 'Rate this article',
    'Оцените статью:': 'Rate this article:',
    'Одобряю статью': 'Approve article',
    'Нейтральное отношение': 'Neutral attitude',
    'Не одобряю статью': 'Disapprove article',
    'Обратная связь по статье': 'Article Feedback',
    'Если вы заметили неточность, хотите предложить идею для улучшения или просто что-то написать, заполните форму ниже.': 'If you noticed an inaccuracy, want to suggest an idea for improvement, or just want to write something, fill out the form below.',
    'Сообщение *': 'Message *',
    'Email (необязательно)': 'Email (optional)',
    'Отправить': 'Submit',
    'Отправляем...': 'Sending...',
    'Спасибо! Сообщение отправлено.': 'Thank you! Message sent.',
    'Не удалось отправить. Попробуйте ещё раз позже.': 'Failed to send. Please try again later.',
    'Пожалуйста, напишите чуть подробнее (минимум 5 символов).': 'Please write a bit more (minimum 5 characters).',
    'Источник данных:': 'Data Source:',
    'Анализ базы данных': 'Analysis of the',
    'WSDC Points Registry': 'WSDC Points Registry',
    'Связанные материалы:': 'Related:',
    'Эволюция правил WSDC': 'Evolution of WSDC Rules',
    'Возвращение правила 3 лет': 'The Return of the 3-Year Rule',
    'Месяцы': 'Months',
    'Переходов в год': 'Transitions per year',
    'Доля за 12 мес.': 'Share within 12 mo.',
    'Поинты': 'Points',
    '2015–19 (база)': '2015–19 (baseline)',
    ' мес.': ' mo.',
    ' п.': ' pts',
    "return (Math.round(v * 10) / 10).toString().replace('.', ',');": "return (Math.round(v * 10) / 10).toString();",
    "if (unit === 'pct') return Number(v).toFixed(1).replace('.', ',') + '%';": "if (unit === 'pct') return Number(v).toFixed(1) + '%';",
    'Сильный сигнал ускорения': 'Strong acceleration signal',
    'Сигнал есть, но мягче': 'Signal present, but milder',
    'Скорость близка к базе': 'Pace close to baseline',
}

es_translations = {
    'Разбираем, не стала ли Skill Level-система WSDC двигаться быстрее, чем меняется соревновательный опыт танцоров.': 'Analizamos si el sistema Skill Level del WSDC ha empezado a moverse más rápido de lo que cambia la experiencia competitiva de los bailarines.',
    'Ускорение переходов между дивизионами: Надо ли что-то делать?': 'Transiciones más rápidas entre divisiones: ¿Hay que hacer algo?',
    'Пороги, поинты и скорость переходов: что изменилось после восстановления календаря WSDC.': 'Umbrales, puntos y velocidad de transición: qué cambió tras la recuperación del calendario del WSDC.',
    'WSDC, West Coast Swing, Skill Level, дивизионы, переход, поинты, Novice, Intermediate, Advanced, All-Star, Champions, аналитика': 'WSDC, West Coast Swing, Skill Level, divisiones, transición, puntos, Novice, Intermediate, Advanced, All-Star, Champions, análisis',
    'Не стала ли Skill Level-система двигаться быстрее, чем растёт соревновательный опыт?': '¿Ha empezado el sistema Skill Level a moverse más rápido de lo que crece la experiencia competitiva?',
    'Разбираем, не стала ли Skill Level-система WSDC двигаться быстрее, чем меняется соревновательный опыт танцоров': 'Analizamos si el sistema Skill Level del WSDC ha empezado a moverse más rápido de lo que cambia la experiencia competitiva de los bailarines',
    'Перейти к содержимому': 'Saltar al contenido',
    '← К главной': '← Volver al inicio',
    'Выбор языка': 'Selección de idioma',
    'Что происходит с переходами между дивизионами, когда ивентов становится больше, а пороги остаются прежними': 'Qué ocurre con las transiciones entre divisiones cuando hay más eventos pero los umbrales siguen igual',
    'После пандемии WSDC-календарь стал активно расти. И вместе с ним изменилось ощущение самой системы дивизионов: поинтов стало больше, возможностей соревноваться — тоже, а путь до следующего дивизиона для части танцоров начал выглядеть короче. Появились случаи, когда танцоры за один календарный год проходят два–три дивизиона, и это перестаёт выглядеть чем-то уникальным.': 'Tras la pandemia, el calendario del WSDC empezó a crecer con fuerza. Con ello cambió la percepción del sistema de divisiones: hubo más puntos, más oportunidades de competir, y para algunos bailarines el camino a la siguiente división empezó a parecer más corto. Ya no es raro que alguien recorra dos o tres divisiones en un solo año calendario.',
    'За 2025 год прошло <strong>172 ивента</strong>, почти <strong>4000 танцоров</strong> получили более <strong>46 тысяч поинтов</strong> — это рекордные показатели за весь период проведения WSDC-ивентов. Текущие показатели 2026 года не дают оснований предполагать, что этот восходящий тренд пойдёт на спад.': 'En 2025 hubo <strong>172 eventos</strong>, casi <strong>4000 bailarines</strong> ganaron más de <strong>46 000 puntos</strong> — cifras récord en toda la historia de eventos del WSDC. Los datos de 2026 no dan motivos para pensar que esta tendencia al alza vaya a revertirse.',
    'В данной статье я хочу рассмотреть существующий механизм регулирования переходов между Skill Level-дивизионами WSDC, а также то, насколько хорошо или плохо текущие пороговые значения справляются с увеличением количества ивентов и танцоров в последние годы, и надо ли что-то с этим делать.': 'En este artículo quiero examinar el mecanismo actual de regulación de transiciones entre divisiones Skill Level del WSDC, cómo están respondiendo los umbrales actuales al aumento de eventos y bailarines en los últimos años, y si conviene hacer algo al respecto.',
    'Почему это важно': 'Por qué importa',
    'Пороги вроде <strong>16 поинтов</strong> для перехода из Novice в Intermediate или <strong>30</strong> из Intermediate в Advanced кажутся технической деталью. Но именно они задают темп: когда человеку уже можно идти в дивизион выше, а когда он должен туда идти.': 'Umbrales como <strong>16 puntos</strong> para pasar de Novice a Intermediate o <strong>30</strong> de Intermediate a Advanced pueden parecer un detalle técnico. Pero marcan el ritmo: cuándo un bailarín puede subir y cuándo debe hacerlo.',
    'Если пороги слишком высокие, танцоры надолго застревают в дивизионе и могут потерять мотивацию. Если слишком низкие — они быстрее получают право идти выше, но не всегда успевают накопить соревновательный опыт и танцевальное мастерство для нового уровня. В обоих случаях вопрос не только в правилах, но и в том, насколько пороги переходов помогают росту, а не просто фиксируют движение по дивизионам.': 'Si los umbrales son demasiado altos, los bailarines se quedan atascados y pueden perder motivación. Si son demasiado bajos, obtienen antes el derecho a subir, pero no siempre acumulan la experiencia competitiva y el nivel necesarios. En ambos casos, la pregunta no es solo de reglas, sino de si los umbrales favorecen el crecimiento y no solo registran el movimiento entre divisiones.',
    'Реестр WSDC учитывает поинты и результаты на соревнованиях. Он не знает, сколько человек тренировался, насколько глубоко он понимает музыку и как выглядит его танец в зале. Поэтому важно отделять две вещи: <strong>скорость продвижения по дивизионам</strong> и <strong>рост танцевального мастерства</strong>. Они связаны, но не обязаны совпадать.': 'El registro del WSDC contabiliza puntos y resultados en competiciones. No sabe cuánto entrenó alguien, qué tan bien entiende la música ni cómo baila realmente. Por eso conviene separar dos cosas: <strong>velocidad de avance entre divisiones</strong> y <strong>crecimiento del nivel de baile</strong>. Están relacionadas, pero no tienen por qué coincidir.',
    'Чтобы понять, почему сравнение с прошлым периодом важно, коротко посмотрим, как менялись правила. С полной хронологией изменений можно ознакомиться в <a href="https://wsdc-analytics.github.io/rules_evolution_2025.html?lang=ru" class="rules-evolution-link">этой статье</a>.': 'Para entender por qué importa comparar con el pasado, repasamos brevemente cómo cambiaron las reglas. La cronología completa está en <a href="https://wsdc-analytics.github.io/rules_evolution_2025.html?lang=ru" class="rules-evolution-link">este artículo</a>.',
    'Как менялись правила переходов': 'Cómo cambiaron las reglas de transición',
    'Установлены базовые пороги переходов по Skill Level: Novice → Intermediate <strong>15</strong> (было 20), Intermediate → Advanced <strong>30</strong> (было 25), Advanced → All-Stars <strong>45</strong> (было 40). Для All-Stars учитываются только Advanced-поинты за <strong>последние 3 года</strong> — не за всю карьеру.': 'Se fijaron los umbrales base de transición Skill Level: Novice → Intermediate <strong>15</strong> (antes 20), Intermediate → Advanced <strong>30</strong> (antes 25), Advanced → All-Stars <strong>45</strong> (antes 40). Para All-Stars solo cuentan los puntos Advanced de los <strong>últimos 3 años</strong>, no toda la carrera.',
    'Вводится система <strong>allowed / required</strong>: Novice <strong>16/30</strong> и Intermediate <strong>30/45</strong> — по сумме поинтов в соответствующем дивизионе; для перехода Advanced → All-Stars — <strong>45/60</strong> Advanced-поинтов, накопленных за <strong>последние 36 месяцев</strong>. WSDC отдельно фиксирует «можно идти выше» и «больше ниже идти не можешь». Изменился механизм, но пороги перехода в дивизион выше остались по сути прежними.': 'Se introduce el sistema <strong>allowed / required</strong>: Novice <strong>16/30</strong> e Intermediate <strong>30/45</strong> según puntos en la división correspondiente; para Advanced → All-Stars — <strong>45/60</strong> puntos Advanced acumulados en los <strong>últimos 36 meses</strong>. El WSDC distingue «puede subir» y «ya no puede quedarse abajo». Cambió el mecanismo, pero los umbrales para pasar a la división superior siguieron siendo esencialmente los mismos.',
    'Для Advanced → All-Stars пороги поднимаются до <strong>60/90</strong>, 36-месячное окно снимается. Novice и Intermediate без изменений: <strong>16/30</strong> и <strong>30/45</strong>. WSDC увеличила пороги перехода из одной номинации в другую, чтобы замедлить трафик переходов из Advanced в All-Stars.': 'Para Advanced → All-Stars, los umbrales suben a <strong>60/90</strong> y se elimina la ventana de 36 meses. Novice e Intermediate sin cambios: <strong>16/30</strong> y <strong>30/45</strong>. El WSDC subió los umbrales para frenar el flujo de Advanced a All-Stars.',
    'Пандемия 2020–2021 годов резко сократила календарь и число переходов. Восстановление после 2023 года наложилось на утверждённые пороги, а рост сообщества в 2025 году поставил вопрос об их актуальности — что косвенно отразилось в <a href="https://wsdc-analytics.github.io/article_3year_rule.html?lang=ru" class="rules-evolution-link">дискуссии</a> о возвращении 36-месячного окна в старшие номинации.': 'La pandemia de 2020–2021 redujo drásticamente el calendario y el número de transiciones. La recuperación tras 2023 coincidió con umbrales ya fijados, y el crecimiento de la comunidad en 2025 planteó dudas sobre su vigencia — reflejado indirectamente en el <a href="https://wsdc-analytics.github.io/article_3year_rule.html?lang=ru" class="rules-evolution-link">debate</a> sobre restaurar la ventana de 36 meses en las divisiones superiores.',
    'Что показывают данные': 'Qué muestran los datos',
    'Возьмём для исследования две метрики:': 'Usaremos dos métricas:',
    '<strong>Время от первого поинта до порога перехода</strong> — сколько времени проходит от первого поинта в дивизионе до получения количества поинтов, позволяющего перейти в следующий дивизион.': '<strong>Tiempo desde el primer punto hasta el umbral de transición</strong> — cuánto tarda desde el primer punto en una división hasta acumular los puntos necesarios para pasar a la siguiente.',
    '<strong>Время между первыми поинтами в дивизионах</strong> — сколько времени проходит от первого поинта в одном дивизионе до первого поинта в следующем дивизионе.': '<strong>Tiempo entre los primeros puntos en divisiones</strong> — cuánto tarda desde el primer punto en una división hasta el primero en la siguiente.',
    'В обоих случаях используется медиана — «серединное» время: у половины танцоров путь занял меньше этого срока, у половины — больше.': 'En ambos casos usamos la mediana — el tiempo «del medio»: la mitad de los bailarines tardó menos y la otra mitad más.',
    'Для сравнения взяты три периода: базовый <strong>2015–2019</strong>, рекордный <strong>2025</strong> и текущий <strong>2026</strong> как показатель текущего тренда. Отдельно показана годовая динамика с 2015 по 2026 год. В фокусе — наиболее стабильные Skill Level-дивизионы: Novice, Intermediate и Advanced.': 'Se comparan tres periodos: base <strong>2015–2019</strong>, año récord <strong>2025</strong> y <strong>2026</strong> actual como indicador de la tendencia. También se muestra la dinámica anual de 2015 a 2026. El foco está en las divisiones Skill Level más estables: Novice, Intermediate y Advanced.',
    '<em>All-Stars и Champions как стартовые дивизионы отдельно не исследовались: для этих номинаций данных недостаточно.</em>': '<em>All-Stars y Champions no se estudiaron por separado como divisiones iniciales: no hay datos suficientes para esas categorías.</em>',
    'Время до порога перехода': 'Tiempo hasta el umbral de transición',
    'Время до порога перехода по годам': 'Tiempo hasta el umbral de transición por año',
    'Время до порога перехода, месяцы по дивизионам': 'Tiempo hasta el umbral de transición, meses por división',
    'Время до порога перехода по годам и дивизионам': 'Tiempo hasta el umbral de transición por año y división',
    'В базовом периоде 2015–2019 на то, чтобы получить право выступать в Intermediate, требовалось примерно <strong>12 месяцев</strong> от получения первого поинта в Novice. На переход из Intermediate в Advanced требовалось <strong>17 месяцев</strong>, а на переход из Advanced в All-Stars — около <strong>20 месяцев</strong>.': 'En el periodo base 2015–2019, obtener el derecho a competir en Intermediate llevaba unos <strong>12 meses</strong> desde el primer punto en Novice. Pasar de Intermediate a Advanced requería <strong>17 meses</strong>, y de Advanced a All-Stars unos <strong>20 meses</strong>.',
    'В 2025 году этот показатель составил <strong>9 месяцев</strong> в Novice, <strong>16 месяцев</strong> в Intermediate и <strong>21 месяц</strong> в Advanced. Тренд 2026 года показывает, что в Novice этот показатель уже ближе к <strong>6 месяцам</strong>, а в Intermediate — к <strong>13</strong>. Главный сигнал здесь — нижняя часть системы стала проходиться быстрее именно там, где пороги давно не менялись.': 'En 2025, esta cifra fue de <strong>9 meses</strong> en Novice, <strong>16 meses</strong> en Intermediate y <strong>21 meses</strong> en Advanced. La tendencia de 2026 muestra Novice ya cerca de <strong>6 meses</strong> e Intermediate cerca de <strong>13</strong>. La señal principal: la parte inferior del sistema avanza más rápido justo donde los umbrales no han cambiado en años.',
    'Время между первыми поинтами в дивизионах': 'Tiempo entre los primeros puntos en divisiones',
    'Время между первыми поинтами по годам': 'Tiempo entre los primeros puntos por año',
    'Время между первыми поинтами в дивизионах, месяцы': 'Tiempo entre los primeros puntos en divisiones, meses',
    'Время между первыми поинтами по годам и дивизионам': 'Tiempo entre los primeros puntos por año y división',
    'По метрике <strong>времени между первыми поинтами в дивизионах</strong> картина согласуется с <strong>временем до порога перехода</strong>, но мягче. В период с 2015 по 2019 год от первого поинта в Novice до первого поинта в Intermediate проходило примерно <strong>17 месяцев</strong>, из Intermediate в Advanced — <strong>21 месяц</strong>, из Advanced в All-Stars — около <strong>25 месяцев</strong>.': 'Según el <strong>tiempo entre los primeros puntos en divisiones</strong>, la imagen coincide con el <strong>tiempo hasta el umbral de transición</strong>, pero de forma más suave. De 2015 a 2019, del primer punto en Novice al primero en Intermediate pasaban unos <strong>17 meses</strong>, de Intermediate a Advanced <strong>21 meses</strong>, y de Advanced a All-Stars unos <strong>25 meses</strong>.',
    'В 2025 году эти показатели составили <strong>15</strong>, <strong>17</strong> и <strong>27 месяцев</strong> соответственно. Тренд 2026 года пока близок к <strong>15 месяцам</strong> на Novice, <strong>17–18</strong> на Intermediate и <strong>28</strong> на Advanced. То есть фактический переход тоже ускоряется на нижних ступенях, но не так резко, как формальное право идти выше.': 'En 2025, estas cifras fueron <strong>15</strong>, <strong>17</strong> y <strong>27 meses</strong> respectivamente. La tendencia de 2026 sigue cerca de <strong>15 meses</strong> en Novice, <strong>17–18</strong> en Intermediate y <strong>28</strong> en Advanced. Las transiciones reales también se aceleran en los escalones inferiores, pero no tan bruscamente como el derecho formal de subir.',
    'Дополнительно важно посмотреть на ещё две вещи: стало ли в целом <strong>больше переходов</strong> между дивизионами и выросла ли <strong>доля тех</strong>, кто получает первые поинты в соседних дивизионах в течение 12 месяцев.': 'Importan dos cosas más: si hay <strong>más transiciones</strong> entre divisiones en general y si creció la <strong>proporción</strong> de quienes obtienen los primeros puntos en divisiones adyacentes en 12 meses.',
    'Число переходов по годам': 'Número de transiciones por año',
    'Доля быстрых переходов за 12 месяцев': 'Proporción de transiciones rápidas en 12 meses',
    'Доля стартовавших, дошедших до следующего дивизиона за 12 месяцев': 'Proporción de quienes llegaron a la siguiente división en 12 meses',
    'Как видно на графиках, в младших дивизионах ускорился не только путь отдельного танцора — расширился и трафик переходов. Количество переходов в <strong>2025</strong> году превысило доковидные показатели, а доля танцоров, которые в течение 12 месяцев успевали получить первые поинты в двух соседних дивизионах, выросла примерно на <strong>5 процентных пунктов</strong> в парах Novice → Intermediate и Intermediate → Advanced от общего числа танцоров, получивших поинты в младшем дивизионе.': 'Como muestran los gráficos, en las divisiones inferiores no solo se aceleró el camino individual — también creció el flujo de transiciones. El número de transiciones en <strong>2025</strong> superó los niveles previos a la pandemia, y la proporción de bailarines que obtuvieron los primeros puntos en dos divisiones adyacentes en 12 meses aumentó unos <strong>5 puntos porcentuales</strong> en los pares Novice → Intermediate e Intermediate → Advanced, respecto al total de bailarines con puntos en la división inferior.',
    'Переходы в старших дивизионах': 'Transiciones en divisiones superiores',
    'WSDC уже пробовала тормозить трафик переходов между Advanced и All-Stars — поэтому он важен как контрольный пример. По метрике <strong>времени между первыми поинтами</strong> для перехода Advanced → All-Stars <strong>не видно такого же сжатия сроков</strong>: медианное время до первых поинтов в All-Stars остаётся сопоставимым с доковидным периодом или даже чуть выше.': 'El WSDC ya intentó frenar el flujo de bailarines entre Advanced y All-Stars — por eso es un caso de control importante. Según el <strong>tiempo entre los primeros puntos</strong> en Advanced → All-Stars, <strong>no hay una compresión comparable de plazos</strong>: la mediana del tiempo hasta los primeros puntos en All-Stars sigue similar al periodo previo a la pandemia o incluso algo mayor.',
    'При этом следует учитывать, что в 2015–2019 порог для перехода в All-Stars был <strong>45</strong> Advanced-поинтов с дополнительным ограничением в виде <strong>36-месячного</strong> окна, а с 2023 года — уже <strong>60</strong> Advanced-поинтов. WSDC подняла планку именно потому, что поток в All-Stars стал слишком быстрым. В <strong>2025–2026</strong> годах медианное время до первых поинтов в All-Stars (<strong>27–28 месяцев</strong>) уже <strong>почти догнало</strong> темп, при котором раньше достигался порог в 45 поинтов (около <strong>25 месяцев</strong> в 2015–2019). Повышение порога пока сдерживает трафик переходов, но приближение к «доковидной» скорости заметно — и это отдельный повод следить за динамикой в старших номинациях.': 'Hay que tener en cuenta que en 2015–2019 el umbral para All-Stars era de <strong>45</strong> puntos Advanced con una ventana adicional de <strong>36 meses</strong>; desde 2023 son <strong>60</strong> puntos Advanced. El WSDC subió la exigencia porque el flujo hacia All-Stars era demasiado rápido. En <strong>2025–2026</strong>, la mediana del tiempo hasta los primeros puntos en All-Stars (<strong>27–28 meses</strong>) ya <strong>casi alcanzó</strong> el ritmo al que antes se llegaba a 45 puntos (unos <strong>25 meses</strong> en 2015–2019). El umbral más alto aún frena ese flujo, pero la aproximación a la velocidad previa a la pandemia es visible — otro motivo para seguir la dinámica en las divisiones superiores.',
    'Вопрос к порогам — без готового ответа': 'Una pregunta sobre los umbrales — sin respuesta lista',
    'Если пороги — лишь формальная отметка («набрал X — можешь идти»), рост переходов может быть естественным следствием более плотного календаря ивентов. Если же пороги — способ сглаживать трафик перехода между дивизионами, то неизменные <strong>16/30</strong> и <strong>30/45</strong> при более плотном графике в младших дивизионах заслуживают обсуждения: совпадает ли темп переходов с тем, какой соревновательный опыт WSDC хочет видеть внутри каждого дивизиона.': 'Si los umbrales son solo una marca formal («acumuló X — puede subir»), más transiciones pueden ser consecuencia natural de un calendario más denso. Si los umbrales sirven para suavizar el flujo entre divisiones, entonces <strong>16/30</strong> y <strong>30/45</strong> sin cambios con un calendario más apretado en divisiones inferiores merece debate: ¿coincide el ritmo de transiciones con la experiencia competitiva que el WSDC quiere en cada división?',
    'Ниже — не рекомендация «поднять до N», а способ показать масштаб сдвига: <em>какими должны быть allowed-пороги, чтобы медианное время вернулось к доковидным значениям 2015–2019 гг.</em>': 'Lo siguiente no es una recomendación de «subir a N», sino una forma de mostrar la magnitud del cambio: <em>qué umbrales allowed harían falta para que la mediana del tiempo volviera a los valores previos a la pandemia de 2015–2019.</em>',
    'Это не новый «лимит скорости» и не проект правила. Это арифметическая иллюстрация: она учитывает только календарную скорость в реестре, но не географию, мотивацию и качество танца.': 'Esto no es un nuevo «límite de velocidad» ni un borrador de regla. Es una ilustración aritmética: solo considera la velocidad calendario en el registro, no la geografía, la motivación ni la calidad del baile.',
    'Какими выглядели бы пороги при старом темпе движения': 'Cómo se verían los umbrales al ritmo antiguo',
    'Текущий порог': 'Umbral actual',
    'Порог с учётом темпа 2025 года': 'Umbral ajustado al ritmo de 2025',
    'Порог с учётом тренда 2026 года': 'Umbral ajustado a la tendencia de 2026',
    'Текущие allowed-пороги и два сценария пересчёта': 'Umbrales allowed actuales y dos escenarios de recálculo',
    'Для того чтобы медианное время набора поинтов в Novice до порога перехода в Intermediate вернулось к доковидным значениям, порог должен быть <strong>21</strong> поинт, а с учётом тренда 2026 года и расчётом на сохранение этого тренда — <strong>30</strong> поинтов. Для перехода из Intermediate в Advanced эти значения составляют <strong>32</strong> и <strong>44</strong> поинта соответственно.': 'Para que la mediana del tiempo de acumulación de puntos en Novice hasta el umbral de Intermediate vuelva a los valores previos a la pandemia, el umbral debería ser de <strong>21</strong> puntos; considerando la tendencia de 2026 y suponiendo que se mantenga, <strong>30</strong> puntos. Para Intermediate → Advanced, esos valores serían <strong>32</strong> y <strong>44</strong> puntos respectivamente.',
    'Почему нельзя «просто поднять пороги»': 'Por qué no se pueden «simplemente subir los umbrales»',
    'Доступ к ивентам распределён неравномерно. В регионах с плотным календарём (США, Европа) более высокий порог может означать «чуть дольше соревноваться». В регионах с несколькими ивентами в год — почти непреодолимый барьер. Любое ужесточение сильнее ударит по тем, у кого меньше возможностей набирать поинты и участвовать в ивентах, а также в развивающихся WCS-регионах.': 'El acceso a eventos está desigualmente repartido. En regiones con calendario denso (EE. UU., Europa), un umbral más alto puede significar «competir un poco más». En regiones con pocos eventos al año, puede ser una barrera casi insuperable. Cualquier endurecimiento golpea más a quienes tienen menos oportunidades de ganar puntos y asistir a eventos, y también a las regiones WCS en desarrollo.',
    'Статья не призывает к конкретному решению. Она показывает, что <strong>скорость продвижения по дивизионам и рост соревновательного мастерства — не одно и то же</strong>: реестр фиксирует поинты и переходы, а не часы в зале. Если сообщество считает, что система дивизионов должна отражать именно соревновательный опыт, а не только доступность ивентов, этот разрыв стоит обсуждать открыто.': 'Este artículo no propone una solución concreta. Muestra que <strong>la velocidad de avance entre divisiones y el crecimiento del nivel competitivo no son lo mismo</strong>: el registro contabiliza puntos y transiciones, no experiencia real de baile. Si la comunidad cree que el sistema de divisiones debe reflejar la experiencia competitiva y no solo la disponibilidad de eventos, conviene debatir abiertamente esta brecha.',
    'Вывод': 'Conclusión',
    'После восстановления календаря ивентов нижняя часть Skill Level-системы WSDC стала проходиться быстрее и для большего количества танцоров, чем в 2015–2019: сжались сроки и до порога перехода, и между первыми поинтами в дивизионах, выросла доля быстрых переходов за год. На Advanced → All-Stars, где WSDC в 2023 году подняла пороги, массового ускорения нет — но темп переходов снова приближается к доковидному.': 'Tras la recuperación del calendario de eventos, la parte inferior del sistema Skill Level del WSDC avanza más rápido para más bailarines que en 2015–2019: se acortaron los plazos hasta el umbral de transición y entre los primeros puntos en divisiones, y creció la proporción de transiciones rápidas en un año. En Advanced → All-Stars, donde el WSDC subió los umbrales en 2023, no hay aceleración masiva — pero el ritmo de transiciones vuelve a acercarse a los niveles previos a la pandemia.',
    'Это не доказательство, что танцоры «не готовы», и не призыв срочно поднять пороги. Реестр считает движение между дивизионами, но не измеряет опыт в зале; любое ужесточение бьёт неравномерно по регионам. Главный вопрос остаётся открытым: <strong>какую скорость движения по дивизионам WSDC считает здоровой</strong> — и где эта скорость перестаёт совпадать с ростом реального танцевального уровня.': 'Esto no demuestra que los bailarines «no estén listos», ni es un llamado a subir urgentemente los umbrales. El registro cuenta el movimiento entre divisiones, pero no mide la experiencia real de baile; cualquier endurecimiento golpea de forma desigual por regiones. La pregunta principal sigue abierta: <strong>qué velocidad de avance entre divisiones considera saludable el WSDC</strong> — y dónde deja de coincidir con el crecimiento real del nivel de baile.',
    'Оценка статьи': 'Calificar el artículo',
    'Оцените статью:': 'Califica este artículo:',
    'Одобряю статью': 'Aprobar artículo',
    'Нейтральное отношение': 'Actitud neutral',
    'Не одобряю статью': 'Desaprobar artículo',
    'Обратная связь по статье': 'Comentarios del artículo',
    'Если вы заметили неточность, хотите предложить идею для улучшения или просто что-то написать, заполните форму ниже.': 'Si notaste una inexactitud, quieres sugerir una idea de mejora o simplemente escribir algo, completa el formulario a continuación.',
    'Сообщение *': 'Mensaje *',
    'Email (необязательно)': 'Email (opcional)',
    'Отправить': 'Enviar',
    'Отправляем...': 'Enviando...',
    'Спасибо! Сообщение отправлено.': '¡Gracias! Mensaje enviado.',
    'Не удалось отправить. Попробуйте ещё раз позже.': 'Error al enviar. Por favor, inténtalo de nuevo más tarde.',
    'Пожалуйста, напишите чуть подробнее (минимум 5 символов).': 'Por favor, escribe un poco más (mínimo 5 caracteres).',
    'Источник данных:': 'Fuente de datos:',
    'Анализ базы данных': 'Análisis del',
    'WSDC Points Registry': 'WSDC Points Registry',
    'Связанные материалы:': 'Material relacionado:',
    'Эволюция правил WSDC': 'Evolución de las reglas del WSDC',
    'Возвращение правила 3 лет': 'El regreso de la regla de los 3 años',
    'Месяцы': 'Meses',
    'Переходов в год': 'Transiciones por año',
    'Доля за 12 мес.': 'Proporción en 12 mes.',
    'Поинты': 'Puntos',
    '2015–19 (база)': '2015–19 (base)',
    ' мес.': ' mes.',
    ' п.': ' pt.',
    'Сильный сигнал ускорения': 'Señal fuerte de aceleración',
    'Сигнал есть, но мягче': 'Hay señal, pero más suave',
    'Скорость близка к базе': 'Ritmo cercano a la base',
}

if __name__ == '__main__':
    translate_file(SOURCE, TARGET_EN, 'en', en_translations)
    translate_file(SOURCE, TARGET_ES, 'es', es_translations)
    print(f'Generated {TARGET_EN} and {TARGET_ES}')
